Feature/css nri
michiko0417/michiko-nakatani pull request #2
Opened 2020-10-17 07:56 UTC by michiko0417

NRI課題のCSS実装

2020-10-17 09:18 UTC, choimake reviewed
確認しました。全体的によくできています。素晴らしいです。

いくつか気になる点があったのでコメントしています。確認の上対応お願いします。

- リセットCSS、もしくはノーマライズCSSを導入してください
異なるブラウザでスタイルがズレるといった事態を防ぐためです。

以下、参考記事になります。
https://www.jungleocean.com/programming/190417reset-normalize-sanitize-css

- 横幅が大きい画面のときにヘッダーのレイアウトが異なっています。

提出ページ
![スクリーンショット 2020-10-17 18 07 30](https://user-images.githubusercontent.com/52233450/96333350-4b5d0380-10a4-11eb-8381-76e94f57ff44.png)
元ページ
![スクリーンショット 2020-10-17 18 07 19](https://user-images.githubusercontent.com/52233450/96333354-4d26c700-10a4-11eb-98e0-c16f3849a938.png)

- メニューホバー時には下線が表示されるようにしてください
![スクリーンショット 2020-10-17 18 07 53](https://user-images.githubusercontent.com/52233450/96333401-a262d880-10a4-11eb-896a-92c9de58b3c9.png)


- SNSのボタンはリンクにしてください
![スクリーンショット 2020-10-17 18 07 42](https://user-images.githubusercontent.com/52233450/96333380-85c6a080-10a4-11eb-9788-caf24cf4be93.png)

2020-10-17 09:18 UTC, choimake commented on html-nri/style.css
> +}
レスポンシブ対応Goodです。
課題の要件には入ってはいませんが、素晴らしい積極性だと思います。

2020-10-17 09:18 UTC, choimake commented on html-nri/style.css
> +
細かいですが、この空白行いらないように見えます。

2020-10-18 09:08 UTC, piasoratech requested changes
- 上段と下段の高さは異なるので本家サイトを参考に修正してください
![image](https://user-images.githubusercontent.com/57445698/96363025-a65a2d80-116c-11eb-9dc2-7e103c76219d.png)

- 同じ場所になりますが、ホバーした時の下線は本家サイトでは出ないので、修正をお願いします(上段・下段ともに)
![image](https://user-images.githubusercontent.com/57445698/96363049-c38efc00-116c-11eb-857a-be71888af827.png)

- このアイコンはホバーした時に透明度が変わるので、本家サイトを参考に修正してください。
![image](https://user-images.githubusercontent.com/57445698/96363072-e9b49c00-116c-11eb-90a8-ecc2f6329d30.png)

2020-10-18 09:08 UTC, piasoratech commented on html-nri/index.html
> +    <link rel="stylesheet" href="normalize.css">
CSSを読み込ませる順番はnormalize > styleの順にしたほうが良いので、style.cssを読み込ませている11行目より上に書くようにしましょう

2020-10-18 13:13 UTC, piasoratech approved these changes
OKです！
次に進みましょう！

2020-10-19 10:14 UTC, merged